export const ALLOWED_INSTITUTIONS = [
  "Algoma University",
  "Brock University",
  "Carleton University",
  "Lakehead University",
  "Laurentian University",
  "McMaster University",
  "Nipissing University",
  "OCAD University",
  "Ontario Tech University",
  "Queen's University",
  "Toronto Metropolitan University",
  "Trent University",
  "University of Guelph",
  "University of Ottawa",
  "University of Toronto",
  "University of Waterloo",
  "University of Windsor",
  "Western University",
  "Wilfrid Laurier University",
  "York University"
];

export const INSTITUTIONAL_EMAIL_DOMAINS = [
  "algomau.ca",
  "brocku.ca",
  "carleton.ca",
  "lakeheadu.ca",
  "laurentian.ca",
  "mcmaster.ca",
  "nipissingu.ca",
  "ocadu.ca",
  "ontariotechu.ca",
  "queensu.ca",
  "torontomu.ca",
  "trentu.ca",
  "uoguelph.ca",
  "uottawa.ca",
  "utoronto.ca",
  "uwaterloo.ca",
  "uwindsor.ca",
  "uwo.ca",
  "westernu.ca",
  "wlu.ca",
  "yorku.ca"
];